algolia/angular-instantsearch

- community-website/src/community-project-boilerplate-docgen/src/widgets/instantsearch.md
- examples/dev-novel/main.ts
- examples/dev-novel/wrap-with-hits.ts
- package.json
- src/create-ssr-algolia-client.ts
- src/index.ts
- src/instantsearch/instantsearch.ts
- yarn.lock
_This PR adds support for the `searchClient` parameter. This allows any Angular InstantSearch user to plug their own search client (including a custom Algolia backend)._
```javascript
import * as algoliasearch from 'algoliasearch/lite';
// With the default Algolia search client
@Component({
selector: 'app-root',
templateUrl: './app.component.html',
})
export class AppComponent {
title = 'app';
config = {
indexName: 'concerts',
searchClient: algoliasearch('appId', 'apiKey')
};
}
// With a custom search client
@Component({
selector: 'app-root',
templateUrl: './app.component.html',
})
export class AppComponent {
title = 'app';
config = {
indexName: 'concerts',
searchClient: {
search(requests) {
return fetchResultsFromRequests(requests);
}
}
};
}
```
* algolia/instantsearch.js#2894
* …
> feat(search-client): Add support for Custom Search Clients

- community-website/src/community-project-boilerplate-docgen/src/getting-started.md
Hello! In using the getting started guide, I came across these changes to the components in the repo which are not reflected in the guide:
- Update widget reference from `CurrentRefinedValues` to `CurrentRefinements` including links to [docs](https://community.algolia.com/angular-instantsearch/widgets/current-refinements.html)
- Update widget reference from `ClearAll` to `ClearRefinements` including links to [docs](https://community.algolia.com/angular-instantsearch/widgets/clear-refinements.html)
> Update: 'Getting Started' guide refinement widgets

- community-website/src/community-project-boilerplate-docgen/src/widgets/infinite-hits.md
**Summary**
closes #126 
In the current documentation of `<ais-infinite-hits></ais-infinite-hits>` we don't implement the show more button. It might be a bit confusing for the user because there is no way to load more pages.
**Results**
https://codesandbox.io/s/8y9lzxv192
> docs(InfiniteHits): show usage with the button

- package.json
- scripts/bump-package-version.js
- scripts/release.js
- yarn.lock
Before this commit, replacements were done in a way that searched the
whole package.json for 2.0.1 and replaced it with 2.0.2.
This is not safe since we are sometime replacing versions of other
packages.
I reused a modified file from other projects (places) to handle this
case.
> chore(release): fix release script

- ng-package.json
- package.json
- rollup.config.umd.js
- src/highlight/highlight.ts
- src/pagination/pagination.ts
- tsconfig.json
- yarn.lock
Lodash + es + angular + rollup is a nightmare. Let's use simple lodash like in instantsearch.js for now so dependencies are shared
> fix(lodash): use normal lodash as in instantsearch.js

- community-website/src/community-project-boilerplate-docgen/webpack.config.build.js
I tested it locally with this version of UglifyJS I don't have the issue. Let see if it works in the preview!
> fix(docs): revert uglifyjs-webpack-plugin to 1.2.5

- community-website/src/community-project-boilerplate-docgen/src/widgets/stats.md
Found typo in stats widget doc
> docs(stats): Fixing code example's wrong variable name

- community-website/src/community-project-boilerplate-docgen/src/widgets/instantsearch.md
- src/instantsearch/instantsearch.ts
According to the [documentation](https://community.algolia.com/angular-instantsearch/widgets/instantsearch.html#config-object-options), the `searchFunction` function takes the `helper` as a parameter.
see #232
> fix(instantSearch) : `searchFunction` param typing

- community-website/src/community-project-boilerplate-docgen/assets/js/main.js
The former DocSearch configuration was a specific index not owned by the DocSearch team. The configuration was not relevant (e.g. if you type `searchClient` or `backend`, no results are showing up).
This new configuration has been set up by @s-pace (huge thanks!) and should be more accurate.
> fix(community): fix DocSearch config

- package.json
- removed malformed >=^5.0.0 syntax
- added support for v7
After the version is release, I'll need to update the examples.
> fix(peerDependencies): allow peer dependencies >=5.0.0 <8.0.0

- package.json
- src/version.ts
- webpack.demo.js
- yarn.lock
NB: this is still work in progress, review at your own risk
followed https://webpack.js.org/migrate/4/:
Also:
> fix(dev-novel): update webpack demo config to support v4

- scripts/build.sh
The purpose of this change is to better detect build failures on dev-novel
Right now, dev-novel is only build in the netlify env, which empirically tends to swallow errors.
for example in this build: https://app.netlify.com/sites/angular-instantsearch/deploys/5bd9987f02ed833a3299b33c
```
1:02:57 PM: One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
1:02:57 PM:  - webpack-cli (https://github.com/webpack/webpack-cli)
1:02:57 PM:    The original webpack full-featured CLI.
1:02:57 PM: We will use "yarn" to install the CLI via "yarn add -D".
1:02:57 PM: Do you want to install 'webpack-cli' (yes/no): Done in 316.25s.
```
you can see that the unaswered prompt did not result in an error.
Ideally this should timeout and eventually fail.
If this …
> fix(build): include dev-novel build as part of the global build command

- examples/angular-router/package.json
- examples/e-commerce/package.json
- examples/media/package.json
- examples/server-side-rendering/package.json
- scripts/build-example.sh
Purpose: make the build-example script more generic
This is preparing the arrival of a new example "storybook", which will replace the dev-novel.
It doesn't build exactly like other angular apps, which is why I'm making the build script more generic
> chore(docs): simplify build script

- examples/storybook/src/stories/RefinementList.stories.ts
- src/refinement-list/__tests__/refinement-list.spec.ts
- src/refinement-list/refinement-list.ts
⚠️  breaking change
Priorly the user could control the display of the show more button with
by acting on the showMoreLimit prop. This internally changed the
canToggleShowMore state which eventually controlled the visibility of the button.
In other flavours it is controlled by an external prop showMore : Boolean.
This PR intends to make the behaviour consistent with other flavours
fixes #391
> fix(RefinementList): introduce showMore prop to hide showmore button

- src/search-box/__tests__/search-box.spec.ts
- src/search-box/search-box.ts
**Summary**
This PR is fixing the broken searchAsYouType property (fixes https://github.com/algolia/angular-instantsearch/issues/375)
**Before:**
When user typed a query into `<ais-search-box [searchAsYouType]="false"></ais-search-box>` and pressed enter, nothing happened
**Now:** 
When user types a query into `<ais-search-box [searchAsYouType]="false"></ais-search-box>` and presses enter, the refine method of the connector is called.
**Result**
> fix(SearchBox): searchAsYouType doesn't work

- examples/storybook/src/stories/QueryRuleContext.stories.ts
- src/configure/__tests__/configure.spec.ts
- src/index.ts
- src/query-rule-context/__tests__/__snapshots__/query-rule-context.spec.ts.snap
- src/query-rule-context/__tests__/query-rule-context.spec.ts
- src/query-rule-context/query-rule-context.module.ts
- src/query-rule-context/query-rule-context.ts
- src/refinement-list/__tests__/refinement-list.spec.ts
This adds the `ais-query-rule-context` widget based on the InstantSearch.js `queryRules` connector.
This depends on #482.
>  feat(queryRules): add ais-query-rule-context widget

- examples/storybook/src/stories/Hits.stories.ts
- examples/storybook/src/stories/QueryRuleContext.stories.ts
- examples/storybook/src/stories/QueryRuleCustomData.stories.ts
- examples/storybook/src/wrap-with-hits.ts
- package.json
- src/configure/__tests__/configure.spec.ts
- src/index.ts
- src/query-rule-context/__tests__/__snapshots__/query-rule-context.spec.ts.snap
- src/query-rule-context/__tests__/query-rule-context.spec.ts
- src/query-rule-context/query-rule-context.module.ts
- src/query-rule-context/query-rule-context.ts
- src/query-rule-custom-data/__tests__/__snapshots__/query-rule-custom-data.spec.ts.snap
- src/query-rule-custom-data/__tests__/query-rule-custom-data.spec.ts
- src/query-rule-custom-data/query-rule-custom-data.module.ts
- src/query-rule-custom-data/query-rule-custom-data.ts
- src/refinement-list/__tests__/refinement-list.spec.ts
- tslint.json
- yarn.lock
This adds the `ais-query-rule-custom-data` widget based on the InstantSearch.js `queryRules` connector.
> feat(queryRules): add ais-query-rule-custom-data widget

- examples/angular-router/package.json
- examples/angular-router/src/app/components/menu-select/menu-select.component.ts
- examples/angular-router/src/app/components/search/search.component.ts
- examples/angular-router/yarn.lock
Main changes to notice are
- connectMenu is now using `attribute` instead of `attributeName` cf. [Instantsearch V2 -> V3 upgrade guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/?language=angular#menu)
- `items`  property of sortBy was previously of type `{name: string, label: string}`, now {value: string, label: string} cf. [Instantsearch V2 -> V3 upgrade guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/?language=angular#sortby)
> chore(examples): migrate angular-router example to v3

- examples/media/package.json
- examples/media/yarn.lock
This is rather fixing the version number in the package.json.
The code of the example has already been migrated.
It didn't look broken because the examples are always built with the "current" angular-instantsearch codebase regardless of the version that is referenced in the package.json. (cf. https://github.com/algolia/angular-instantsearch/blob/756862922ee240aced3d82fa985f4a20dc4b1815/scripts/build-example.sh)
> chore(examples): migrate media example to v3 (#485)

- src/__tests__/create-ssr-algolia-client.spec.ts
- src/create-ssr-algolia-client.ts
- src/instantsearch/__tests__/instantsearch.spec.ts
- src/instantsearch/instantsearch.ts
**Summary**
Update UA to `angular ($VERSION); angular-instantsearch ($VERSION)`
Add the `addAlgoliaAgent` to `SearchClient` and fix the issue where the UA is **only** added when the `SearchClient` is not passed in config
**Result**
> fix(ua): change the User-Agent to use the new specs lib (version)

- src/hits/__tests__/__snapshots__/hits.spec.ts.snap
- src/hits/__tests__/hits.spec.ts
This PR adds tests for make sure `ais-hits` works with `<ng-template>`
and that it's passing `hits` and `results` like we want to.
This is a fairly common use case and yet we do not test it.
I noticed this as I was attempting to write tests for the insights
integration.
> fix(Hits): add test for template support

- examples/angular-router/package.json
- examples/angular-router/src/app/components/search/search.component.ts
- examples/angular-router/yarn.lock
- examples/e-commerce/package.json
- examples/e-commerce/src/app/app.component.html
- examples/e-commerce/src/app/app.component.ts
- examples/e-commerce/yarn.lock
- examples/media/package.json
- examples/media/src/app/app.component.html
- examples/media/src/app/app.component.ts
- examples/media/yarn.lock
- examples/storybook/package.json
- examples/storybook/src/wrap-with-hits.ts
- examples/storybook/yarn.lock
- src/instantsearch/__tests__/instantsearch.spec.ts
- src/instantsearch/instantsearch.ts
This enforces the `searchClient` option for Angular InstantSearch v3 and drops support for `appId` and `apiKey`. This change is necessary to be aligned with other InstantSearch flavors. It also removes `createAlgoliaClient` which is replaced by `searchClient`.
- All examples were updated (there's some noise because some files were not formatted).
- The storybook was updated to use `searchClient`. It can still be overridden internally in the stories if you pass `appId` and `apiKey`.
- I didn't update `createSSRSearchClient` in this PR.
[See examples →](https://deploy-preview-496--angular-instantsearch.netlify.com/examples.html)
>  feat(searchClient): enforce search client

- examples/storybook/src/stories/RangeInput.stories.ts
- src/range-input/__tests__/__snapshots__/range-input.spec.ts.snap
- src/range-input/__tests__/range-input.spec.ts
- src/range-input/range-input.ts
**Summary**
Prior to this fix it was not possible to use precision 0
```html
<ais-range-input attribute="price" precision="0"></ais-range-input>
```
And so it was not possible to produce steps of size `1`.
Closes https://github.com/algolia/angular-instantsearch/issues/374
> fix(RangeInput): allow precision of 0

- examples/storybook/src/stories/Hits.stories.ts
- examples/storybook/src/wrap-with-hits.ts
- src/hits/__tests__/hits.spec.ts
- src/hits/hits.ts
**Summary**
This integrates insights with Angular Instantsearch to help using Click Analytics in Hits.
Using `connectHitsWithInsights` instead of `connectHits` exposed a new property `insights` to the internal state, which user can call to emit insights events.
**Result**
```html
<ais-hits>
<ng-template let-hits="hits" let-insights="insights">
<div *ngFor="let hit of hits">
<ais-highlight attribute="name" [hit]="hit"></ais-highlight>
<button (click)="insights('clickedObjectIDsAfterSearch', { eventName: 'Add to cart', objectIDs: [hit.objectID] })">
Add to favorite
</button>
</div>
</ng-template>
</ais-hits>
```
> feat(insights): add insights support to Hits widget

- examples/storybook/src/stories/InfiniteHits.stories.ts
- src/infinite-hits/__tests__/__snapshots__/infinite-hits.spec.ts.snap
- src/infinite-hits/__tests__/infinite-hits.spec.ts
- src/infinite-hits/infinite-hits.ts
⚠️  This PR can't work until https://github.com/algolia/angular-instantsearch/pull/492 and https://github.com/algolia/angular-instantsearch/pull/491 are merged. It will stay as draft until then.
**Summary**
This integrates insights with Angular Instantsearch to help using Click Analytics in InfiniteHits.
Using `connectInfiniteHitsWithInsights` instead of `connectInfiniteHits` exposed a new property `insights` to the internal state, which user can call to emit insights events.
**Result**
```html
<ais-infinite-hits>
<ng-template let-hits="hits" let-insights="insights">
<div *ngFor="let hit of hits">
<ais-highlight attribute="name" [hit]="hit"></ais-highlight>
<button (click)="insights('clickedObjectIDsAfterSearch', { eventName: 'Add to cart', objectIDs: [hit.objectID] })">
Add to favorite …
```
> feat(insights): add insights support to InfiniteHits widget

- helpers/test-renderer.ts
⚠️  This PR is stacked on #498 for convenience.
This serves usecases for testing parameters of type Function.
This code snippets demonstrates it:
```ts
const transformItems = jest.fn()
const render = createRenderer({
defaultState,
template: '<ais-breadcrumb></ais-breadcrumb>',
TestedWidget: NgAisBreadcrumb,
methods: {
transformItems,
}
});
const fixture = render();
expect(fixture.componentInstance.testedWidget.transformItems).toEqual(transformItems)
```
This imitates what we can find in the [`wrapWithHits` function from the storybook example](https://github.com/algolia/angular-instantsearch/blob/develop/examples/storybook/src/wrap-with-hits.ts#L12).
> chore(tests): add support for passing methods in createRenderer

- community-website/src/community-project-boilerplate-docgen/layouts/common/meta.pug
**Summary**
We introduce [the canonical URLs](https://github.com/algolia/angular-instantsearch/pull/467/files) to keep backlinks to the algolia.com/doc. But it's not enough to make the Community website disappear from the search results. We have to hide them from the search results otherwise it's confusing for users.
https://github.com/algolia/instantsearch.js/pull/3748
> chore: disable canonical link

- examples/storybook/src/stories/HierarchicalMenu.stories.ts
**Summary**
This adds a missing example showcasing transformItems usage in HierarchicalMenu.
I noticed this was missing when I migrated the widget to use transformItems provided by the connector.
**Result**
https://deploy-preview-559--angular-instantsearch.netlify.com/examples/storybook/?path=/story/hierarchicalmenu--with-transformitems
> docs(HierarchicalMenu): add example showcasing transformItems

- src/hierarchical-menu/__tests__/hierarchical-menu.spec.ts
**Summary**
This helps changing the template from one test to the other.
It prepares for tests I'll write checking how props declared on the
widget are passed to the connector as instance props.
I isolated them in a separate PR.
**Results**
Nothing should change
> style(HierarchicalMenu): move test render method inside tests

- examples/storybook/src/stories/NumericMenu.stories.ts
- src/numeric-menu/__tests__/numeric-menu.spec.ts
- src/numeric-menu/numeric-menu.ts
**Summary**
This migrates NumericMenu to use the transformItems provided by the connector. It also removes the test related and replaces it with one that checks all instance options are correctly applied to the connector.
**Result**
https://deploy-preview-560--angular-instantsearch.netlify.com/examples/storybook/?path=/story/numericmenu--with-transformitems
ref https://github.com/algolia/angular-instantsearch/issues/372
> fix(NumericMenu): use connector transformItems 

- examples/storybook/src/stories/ClearRefinements.stories.ts
- src/clear-refinements/__tests__/clear-refinements.spec.ts
- src/clear-refinements/clear-refinements.ts
**Summary**
This migrates ClearRefinements to use the transformItems provided by the connector.
- improves the typing
- changes `createURL` default to `() => '#'`
- adds a storybook example for transformItems
⚠️ if you think there are too many changes, I can split it up.
ref https://github.com/algolia/angular-instantsearch/issues/372
> fix(ClearRefinements): use connector transformItems

- src/infinite-hits/infinite-hits.ts
**Summary**
Introduced `InfiniteHitsState` and `InfiniteHitsItem`.
I could have copy pasted some of the types we have in InstantSearch V3 but they are IO believe a little complex and will certainly be subject to changes.
I'm afraid if we systematically copy paste the types we have currently in IS V3 we'll just end up maintaining them in two different places or with a lot of inconsistencies.
Ideally IS V3 would allow importing the types and use them here directly. In the mean time, the idea is to keep Angular IS types very simple so they'll be easier to migrate to IS's complex types.
**Result**
N/A
> fix(InfiniteHits): improve typing

- src/hits/__tests__/hits.spec.ts
- src/hits/hits.ts
⚠️ This PR is stacked on top of https://github.com/algolia/angular-instantsearch/pull/551 and follows up on https://github.com/algolia/angular-instantsearch/pull/551#discussion_r284146310
**Summary**
- feat(Hits): expose escapeHTML instance option This exposed `escapeHTML` on the ais-hits.
https://www.algolia.com/doc/api-reference/widgets/hits/js/#widget-param-escapehtml
**Usage**
```ts
<ais-hits [escapeHTML]="false">
<ng-template let-hits="hits">
<div *ngFor="let hit of hits">
<span [innerHTML]="hit.name"></span>
</div>
</ng-template>
<ais-hits>
```
- docs(Hits): add story for escapeHTML in hits
**Result**
// to be added
>  feat(Hits): expose escapeHTML instance option 

- examples/storybook/src/wrap-with-hits.ts
**Summary**
This PR passes `styles` prop to wrapped component.
This is to provide a way to add story-specific styles, not polluting the global style.
The type of `styles` has changed from `?: string` to `?: string[]`, but there were no use case at all.
So it's safe to change like this.
> chore(storybook): pass styles prop to wrapped component

- scripts/build-example.sh
- scripts/netlify.sh
**Summary**
This removes duplicated builds on netlify.
It will build the package once in `netlify.sh` and each `build-example.sh` will skip it due to the new environment variable `SKIP_PACKAGE_BUILD`.
**Why?**
It's slow when deploying on netlify.
`netlify.sh` builds four examples, which executes `build.sh` four times.
Inside `build.sh`, it builds the package(`yarn && yarn build`).
It means `yarn && yarn build` is executed every time `build.sh` runs,
which means it's duplicated, unnecessary and slow.
Before starting to build four examples, we should just run `yarn && yarn build` once and
let `build.sh` skip it.
**Result**
On my local machine,
```
before this commit
real    2m11.944s
user    3m18.983s
sys     0m16.899s
after
real    1m36.704s
user    2m30.385s
sys     0m12.814s
```
I diffed …
> chore: remove duplicated builds on netlify

- src/rating-menu/__tests__/__snapshots__/rating-menu.spec.ts.snap
- src/rating-menu/rating-menu.ts
**Summary**
This adds additional class names to `svg` elements in `ais-rating-menu` component.
There was a lack of `ais-RatingMenu-starIcon--full` and `ais-RatingMenu-starIcon--empty` according to [the spec](https://instantsearch-css.netlify.com/widgets/rating-menu/).
**Result**
The `svg` elements now should have `ais-RatingMenu-starIcon` and one of `ais-RatingMenu-starIcon--full` and `ais-RatingMenu-starIcon--empty` as class names.
> chore(ratingMenu): add additional classnames

- src/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
- src/pagination/pagination.ts
**Summary**
According to [the spec](https://instantsearch-css.netlify.com/widgets/pagination/), the default value of `showLast` of `ais-pagination` is supposed to be `true`, which isn't at the moment. This PR fixes this.
**Result**
The default value of `showLast` of `ais-pagination` becomes `true`.
> fix(pagination): set showLast as true by default

- src/toggle/__tests__/__snapshots__/toggle.spec.ts.snap
- src/toggle/__tests__/toggle.spec.ts
- src/toggle/toggle.ts
**Summary**
closes #615
This PR fixes a bug that clicking checkbox didn't update the checkbox itself.
It also updates the dom output to align with [the spec](https://instantsearch-css.netlify.com/widgets/toggle-refinement/). It didn't have unnecessary ul and li elements wrapping the label.
> fix(toggle): update checkbox when clicking the checkbox itself

- examples/e-commerce/angular.json
- examples/e-commerce/src/app/app.component.html
- examples/e-commerce/src/app/app.module.ts
- examples/e-commerce/src/app/no-results.css
- examples/e-commerce/src/app/no-results/no-results.component.ts
This adds the empty state when no hits are returned by the engine. It doesn't change the SFFV no results design.
related to: https://github.com/algolia/instantsearch.js/pull/3894
based on: https://github.com/algolia/react-instantsearch/pull/2601
If no filter are applied, the empty message asks the user to change the query. If there are filters applied, the empty message shows a different message and offers the user to clear the filters.
I added `removeWordsIfNoResults` to `allOptional` so that results are returned most of the time.
- [Preview with only query leading to empty results](https://deploy-preview-634--angular-instantsearch.netlify.com/examples/e-commerce/?query=hellll)
- [Preview with filters leading to empty results](https://deploy-preview-634--angular-instantsearch.netlify.com/ …
> chore(examples): add design for empty result at e-commerce demo

- src/__tests__/utils.spec.ts
- src/utils.ts
**Summary**
This is needed for adding CSS classes such as `ais-Pagination--noRefinement`
(referenced here: https://instantsearch-css.netlify.com/widgets/pagination/)
**Result**
```js
// before
expect(cx('', 'noRefinement')).toBe('ais-Pagination');
// after
expect(cx('', 'noRefinement')).toBe('ais-Pagination--noRefinement');
```
> chore(bem): allow subElements on root CSS class

- package.json
- yarn.lock
This PR updates InstantSearch.js to [3.5.4](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#354-2019-07-01).
> chore(deps): update InstantSearch.js to 3.5.4

- src/rating-menu/__tests__/__snapshots__/rating-menu.spec.ts.snap
- src/rating-menu/__tests__/rating-menu.spec.ts
- src/rating-menu/rating-menu.ts
**Summary**
This adds `ais-StarRating--noRefinement` CSS class on root when items === [].
This is specified in https://instantsearch-css.netlify.com/widgets/rating-menu/
This similar to InstantSearch.JS implementation, which is using the RefinementList component:
https://github.com/algolia/instantsearch.js/blob/b6ee2596d353ea692d91929759bc2b2fe34945c7/src/components/RefinementList/RefinementList.js#L226-L228
Vue InstantSearch does not implement it: https://github.com/algolia/vue-instantsearch/blob/aa7ba065d897b9a5654b04f6bbd23818eaf83baa/src/components/RatingMenu.vue#L4
React InstantSearch is using facet count https://github.com/algolia/react-instantsearch/blob/05a85b61d6e3e3e946c07d05f26fe38289c9920a/packages/react-instantsearch-core/src/connectors/connectRange.js#L247
> fix: add ais-RatingMenu--noRefinement CSS class on root when items === []

- src/range-input/__tests__/__snapshots__/range-input.spec.ts.snap
- src/range-input/__tests__/range-input.spec.ts
- src/range-input/range-input.ts
**Summary**
This adds `ais-RangeInput--noRefinement` CSS class on root when min === max.
This is specified in https://instantsearch-css.netlify.com/widgets/range-input/
Currently every flavour is doing it its won way:
[InstantSearch.JS](https://github.com/algolia/instantsearch.js/blob/b6ee2596d353ea692d91929759bc2b2fe34945c7/src/components/RangeInput/RangeInput.js#L40) is the following condition: `Boolean(min || max)`.
[React InstantSearch](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectRange.js#L247) is using facet count to enable this CSS class but this is not exposed in InstantSearch Connector.
[Vue InstantSearch](https://github.com/algolia/vue-instantsearch/blob/ceeecefa9948526f0518a00eb68563298fcdb7bb/src/components/R …
>  fix: add ais-RangeInput--noRefinement CSS class on root when min === max

- src/pagination/__tests__/__snapshots__/pagination.spec.ts.snap
- src/pagination/__tests__/pagination.spec.ts
- src/pagination/pagination.ts
**Summary**
This adds ais-Pagination--noRefinement CSS class on root when nbPages <= 1
`ais-Pagination--noRefinement` is specificed here: https://instantsearch-css.netlify.com/widgets/pagination/
It is missing at the moment, which makes sharing CSS styles for demos harder.
The CSS class is enabled when nbPages <= 1. This is similar to the condition found in [React InstantSearch](https://github.com/algolia/react-instantsearch/blob/99ed761dc0536fafb884727ed593ee0906b80b7a/packages/react-instantsearch-core/src/connectors/connectPagination.js#L67)
**Result**
No visible effect
> fix: add `ais-Pagination--noRefinement` CSS class on root when nbPages <= 1

- src/rating-menu/__tests__/__snapshots__/rating-menu.spec.ts.snap
- src/rating-menu/rating-menu.ts
**Summary**
This is fixing a sizing/positioning issue on RatingMenu.
I found that it came from the width and height we are setting on the
symbols.
It seems they've always been there https://github.com/algolia/angular-instantsearch/commit/fa8fe63ef9d2bbad78bc2e34f6b0e998a811f8d3
but they were not specified in [InstantSearch.css](https://instantsearch-css.netlify.com/widgets/rating-menu/)
This will need to be ported to v2
**Result**
Before
After
Closes #658
> fix(StarRating): fix overflowing symbols

- src/__tests__/create-ssr-algolia-client.spec.ts
- src/create-ssr-algolia-client.ts
This would be needed for us to put a proxy between Algolia and our frontend to track impressions more effectively on the backend.
**Summary**
I want to set up `hosts.read` and `hosts.write` to setup my proxy host, which will track product ids returned for a set of filters and etc.
Additionally, we will use more than one Algolia cluster so my `proxy` would balance between them without client modifications.
**Result**
> feat: add possibility to set params for the client

- src/__tests__/create-ssr-search-client.spec.ts
- src/create-ssr-search-client.ts
This would be needed for us to put a proxy between Algolia and our frontend to track impressions more effectively on the backend.
**Summary**
I want to set up `hosts.read` and `hosts.write` to setup my proxy host, which will track product ids returned for a set of filters and etc.
Additionally, we will use more than one Algolia cluster so my `proxy` would balance between them without client modifications.
Same as #714
**Result**
> feat(ssr): forward options to search client

- .circleci/config.yml
- CONTRIBUTING.md
- package.json
**Summary**
This PR simplifies the command we run to prepare a release.
- Before: `yarn run release:prepare`
- After: `yarn run release`
On CircleCI, it used to run `yarn run release:trigger`, but now it runs `yarn shipjs trigger`.
related to: https://github.com/algolia/instantsearch.js/pull/4419
> chore: update release script name

- examples/storybook/.storybook/styles.css
- examples/storybook/src/stories/ConfigureRelatedItems.stories.ts
- src/configure-related-items/__tests__/__snapshots__/configure-related-items.spec.ts.snap
- src/configure-related-items/__tests__/configure-related-items.spec.ts
- src/configure-related-items/configure-related-items.module.ts
- src/configure-related-items/configure-related-items.ts
- src/index.ts
**Summary**
Not every UI for which Algolia can be used leans itself to a search interface, this widget is useful for a "related items" list, e.g. on a product page
**Result**
A new widget: `ais-configure-related-items`, to be used inside a separate `ais-index`, with a hit as target and `ais-hits` as its UI.
> feat(widgets): introduce `ConfigureRelatedItems` as experimental

- package.json
There seem to be no required changes for Angular 13 to build, as you can see in https://github.com/Haroenv/angular-instantsearch-angular-13
I did not update the build dependencies to Angular 13, as it required some more changes that we can do later, the current version is usable as-is in angular 5 (possibly only from 8) - 14
fixes #885
> feat(dependencies): allow Angular 13

- package.json
**Summary**
This PR updates the range of versions of Angular we are compatible with, to allow users to use Angular InstantSearch with the newly released Angular 14.
I performed an upgrade on a fresh `create-instantsearch-app` template and started the project without issues.
**Result**
Angular 14 is now allowed as a peer dependency of Angular InstantSearch.
Fixes https://github.com/algolia/angular-instantsearch/issues/954
> chore: update peer dependencies range to allow angular 14

- src/reverse-highlight/reverse-highlight.ts
- src/reverse-snippet/reverse-snippet.ts
- src/snippet/snippet.ts
**Summary**
In the previous implementation, inputs for `<ais-snippet>`, `<ais-reverse-highlight>` and `<ais-reverse-snippet>` were wrongly set to `private readonly` which would prevent a user from effectively setting those during implementation.
This PR removes those access modifiers.
**Result**
The widgets can now be used without fail.
> fix(widgets): remove private access modifier on widgets inputs

- package.json
- yarn.lock
**Summary**
This PR updates the **instantsearch.js** dependency to allow the `<ais-hierarchical-menu>` widget to retrieve and display the full list of a refined item's parents values.
> fix(ais-hierarchical-menu): show full hierarchical parent values

- src/search-box/__tests__/search-box.spec.ts
- src/search-box/search-box.ts
**Summary**
JIRA: [FX-1590](https://algolia.atlassian.net/browse/FX-1590)
This PR prevents state from overriding the query value in a search box if it still has focus. This can happen in a search-as-you-type environment when network speed is low and a user keeps on typing a query while requests are resolved.
> fix(searchbox): prevent concurrent query updates from state while input is focused

- src/search-box/__tests__/__snapshots__/search-box.spec.ts.snap
- src/search-box/__tests__/search-box.spec.ts
- src/search-box/search-box.ts
**Summary**
Work Item : [FX-377](https://algolia.atlassian.net/browse/FX-377)
To stay as close as `InstantSearch.js`'s interface as possible, we decided to add a `showLoadingIndicator` prop which is `true` by default.
The only difference is that we are not able to provide a custom component, which is not feasible for submit/reset buttons anyway.
**Result**
By default, when search is stalled, the reset button will be hidden, and a loading indicator is shown.
If `showLoadingIndicator` is set to false, it will never show a loading indicator, and the reset button will still be present if search is stalled.
> feat(search-box): add loading indicator + `showLoadingIndicator` prop

- package.json
- src/hits-per-page/hits-per-page.ts
- src/numeric-menu/numeric-menu.ts
- src/sort-by/sort-by.ts
- yarn.lock
**Summary**
Following the implementation of [FX-740](https://algolia.atlassian.net/browse/FX-740), this breaks typing for some widget's initial state.
Therefore I updated the `instantsearch.js` dependency and fixed the typings so that others don't have to deal with it.
**Result**
Updated instantsearch.js and fixed initial state typings for multiple widgets
> chore: update `instantsearch.js` and fix typings

- package.json
**Summary**
This PR updates the range of versions of Angular we are compatible with, to allow users to use Angular InstantSearch with the newly released Angular 15.
**Result**
Angular 15 is now allowed as a peer dependency of Angular InstantSearch.
> feat: support angular 15 through peerDependencies

- README.md
- examples/server-side-rendering/README.md
- src/instantsearch/instantsearch.ts
**Summary**
This PR adds mentions of Angular InstantSearch being deprecated:
- in the readme
- in the console when using `<ais-instantsearch>` in an Angular application (only in dev mode)
[FX-2913](https://algolia.atlassian.net/browse/FX-2913)
[FX-2913]: https://algolia.atlassian.net/browse/FX-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: show deprecation warning in dev mode
