algolia/angular-instantsearch

src/search-box/search-box.ts
=> fix(search-box): update markup to match instantsearch.css

src/base-widget.ts, src/results/__tests__/__snapshots__/results.spec.ts.snap, src/results/results.ts
This seems to be a typo, does changing it have a public impact?
=> chore: plateformId -> platformId

src/hits-per-page/__tests__/__snapshots__/hits-per-page.spec.ts.snap, src/hits-per-page/hits-per-page.ts, src/hits/__tests__/__snapshots__/hits.spec.ts.snap, src/hits/hits.ts
=> fix(widgets): replace results by hits

community-website/src/community-project-boilerplate-docgen/src/guides/highlighting-results.md, examples/e-commerce/src/app/app.component.html
=> docs(examples): fix ecommerce example using attributeName

src/hits/hits.ts, src/infinite-hits/infinite-hits.ts, src/range-slider/range-slider.ts, tsconfig-aot.json
=> Fix compile with strict rules

.editorconfig, CONTRIBUTING.md, examples/angular-router/package.json, examples/angular-router/src/styles.scss, examples/angular-router/yarn.lock, examples/e-commerce/package.json, examples/e-commerce/src/styles.scss, examples/e-commerce/yarn.lock, examples/media/package.json, examples/media/src/styles.scss, examples/media/yarn.lock, examples/server-side-rendering/package.json, examples/server-side-rendering/src/styles.scss, scripts/build-example.sh, scripts/run-example.sh
- fixed yarn link place
- simplified css imports (see https://github.com/webpack-contrib/sass-loader#imports)
=> chore(examples): fix running examples

community-website/src/community-project-boilerplate-docgen/src/guides/customize-widgets.md
- typos
- missing import step of new component
=> Improve custom widget documentation

examples/dev-novel/main.ts, src/instantsearch/instantsearch.ts
=> perf(size): use lite client

examples/dev-novel/custom-widgets.ts, examples/dev-novel/main.ts, src/instantsearch/instantsearch.ts
Fixes #185
I edited this on the web interface, so maybe some tests need to be changed too, didn't look into that yet.
=> feat(core): add the refresh method to the InstantSearchInstance signature

community-website/src/community-project-boilerplate-docgen/src/guides/server-side-rendering.md
=> docs(ssr): Use `searchClient`

src/instantsearch/instantsearch.ts
=> fix(types): return array in search client SFFV

community-website/src/community-project-boilerplate-docgen/src/guides/customize-widgets.md
=> docs(guides): fix custom widget showcase link

package.json, yarn.lock
ref https://github.com/algolia/instantsearch.js/issues/984#issuecomment-427830179
=> fix(lodash) unpinned dependency

community-website/src/community-project-boilerplate-docgen/src/widgets/clear-refinements.md, community-website/src/community-project-boilerplate-docgen/src/widgets/configure.md, community-website/src/community-project-boilerplate-docgen/src/widgets/current-refinements.md, community-website/src/community-project-boilerplate-docgen/src/widgets/hierarchical-menu.md, community-website/src/community-project-boilerplate-docgen/src/widgets/highlight.md, community-website/src/community-project-boilerplate-docgen/src/widgets/hits-per-page.md, community-website/src/community-project-boilerplate-docgen/src/widgets/hits.md, community-website/src/community-project-boilerplate-docgen/src/widgets/infinite-hits.md, community-website/src/community-project-boilerplate-docgen/src/widgets/instantsearch.md, community-website/src/community-project-boilerplate-docgen/src/widgets/menu.md, community-website/src/community-project-boilerplate-docgen/src/widgets/numeric-menu.md, community-website/src/community-project-boilerplate-docgen/src/widgets/numeric-selector.md, community-website/src/community-project-boilerplate-docgen/src/widgets/pagination.md, community-website/src/community-project-boilerplate-docgen/src/widgets/range-input.md, community-website/src/community-project-boilerplate-docgen/src/widgets/range-slider.md, community-website/src/community-project-boilerplate-docgen/src/widgets/rating-menu.md, community-website/src/community-project-boilerplate-docgen/src/widgets/refinement-list.md, community-website/src/community-project-boilerplate-docgen/src/widgets/search-box.md, community-website/src/community-project-boilerplate-docgen/src/widgets/sort-by.md, community-website/src/community-project-boilerplate-docgen/src/widgets/toggle.md
followed up on #297 comment from @francoischalifour
=> fix(doc) typo

.circleci/config.yml, community-website/package.json, community-website/yarn.lock, package.json, yarn.lock
=> chore(deps): batch update

src/infinite-hits/__tests__/__snapshots__/infinite-hits.spec.ts.snap, src/infinite-hits/__tests__/infinite-hits.spec.ts, src/infinite-hits/infinite-hits.ts
**Before**
**After**
fixes #406
=> fix(InfiniteHits): change showMore button class to `ais-InfiniteHits-loadMore`

README.md
[package.json](https://github.com/algolia/angular-instantsearch/blob/develop/package.json) says "@angular/common": ">=5.0.0 <8.0.0"
=> fix(doc): update README.md

src/pagination/pagination.ts
**Summary**
just a small comment with a typo in it
**Result**
typo is fixed
=> chore(spelling): fix a small typo

community-website/src/community-project-boilerplate-docgen/layouts/common/header.pug, community-website/src/community-project-boilerplate-docgen/layouts/common/marketing.pug, community-website/src/community-project-boilerplate-docgen/src/stylesheets/components/_banner.sass, community-website/src/community-project-boilerplate-docgen/src/stylesheets/index.sass
**Summary**
This adds a banner to community docs on all pages.
**Result**
https://5c6a7c4b40c9670008913c0b--angular-instantsearch.netlify.com/
=> chore(banner): add V3 beta banner

.circleci/config.yml, examples/server-side-rendering/__tests__/ssr.spec.ts, examples/server-side-rendering/package.json, examples/server-side-rendering/webpack.server.config.js, examples/server-side-rendering/yarn.lock, package.json, scripts/test-example.sh
This adds some basic testing for SSR?
I basically tests two cases:
- SSR when accessing `/`
- SSR when accessing a specific page number `/?p=*`
=> chore(tests): add tests for ssr

community-website/src/community-project-boilerplate-docgen/src/guides/customize-widgets.md
fixes https://github.com/algolia/angular-instantsearch/issues/477
=> chore(docs): fix MenuSelect link

community-website/src/community-project-boilerplate-docgen/src/stylesheets/components/_banner.sass, community-website/src/community-project-boilerplate-docgen/src/stylesheets/header.css
=> chore(docs): fix banner

examples/storybook/src/stories/QueryRuleContext.stories.ts, examples/storybook/src/stories/QueryRuleCustomData.stories.ts
This updates the Query Rules stories as discussed in https://github.com/algolia/angular-instantsearch/pull/483#discussion_r275107501.
=> fix(stories): update Query Rules stories

package.json, yarn.lock
This PR should allow starting implementing InfiniteHits previous button and other features newly released.
=>  chore(deps): update dependency instantsearch to v3.4.0

examples/storybook/.storybook/addons.js, examples/storybook/package.json, examples/storybook/yarn.lock
This PR updates storybook to v5.
It also introduced the action addon that I need to use for insights.
=> chore(deps):  update storybook & introduce actions addon

CONTRIBUTING.md
**Summary**
This fixes a typo on the contributing guide.
**Result**
=> chore(docs): fix a typo on the contributing guide

examples/storybook/src/stories/Hits.stories.ts
**Summary**
* add Hits story showcasing transformItems
**Result**
https://deploy-preview-552--angular-instantsearch.netlify.com/examples/storybook/?path=/story/hits--with-transformitems
=> fix(Hits): add Hits story showcasing transformItems

scripts/release.js
**Summary**
The release script didn't push tags when releasing beta, while it pushs tags when releasing stable.
**Result**
=> chore: push git tags on beta release

src/__tests__/utils.spec.ts, src/range-slider/__tests__/__snapshots__/range-slider.spec.ts.snap, src/utils.ts
**Summary**
This adds tests for bem at utils which was missing.
=> test(utils): add tests for bem

examples/e-commerce/src/app.css
This adds style to app.css to wrap words.
Propagated from https://github.com/algolia/instantsearch.js/pull/3913
=> chore(examples): add app style for word wrap in e-commerce demo

CONTRIBUTING.md, helpers/test-renderer.ts
**Summary**
Some spelling was wrong
**Result**
no longer wrong
=> chore(spelling): update mistakes

src/base-widget.ts, src/voice-search/voice-search.ts
**Summary**
- BaseWidget needs to explicitly allow IndexWidget as it doesn't technically extend widget anymore
- BaseWidget needs to allow a generic state, for voice widget (first/only one that actually declares the state)
**Result**
no type errors on https://github.com/Khbero/sample-app
=> fix(BaseWidget): allow declared state and index widgets

examples/storybook/package.json, examples/storybook/src/custom-widgets.ts, examples/storybook/src/stories/CustomWidgets.stories.ts, examples/storybook/yarn.lock
**Summary**
the examples of custom widgets were still using BaseWidget, and not initialising the state like other examples
**Result**
working storybook
=> fix(stories): usage of TypedBaseWidget in custom widgets

ship.config.js
**Summary**
Update Ship.js config to work with `master` branch and deleting the `develop` branch.
Closes https://algolia.atlassian.net/browse/FX-757
=> chore: update shipjs config to work with master

src/pagination/__tests__/pagination.spec.ts, src/pagination/pagination.ts
=> fix(pagination): use pages computed in connector

ship.config.js
**Summary**
Releases threw an error because the previous team does not exist anymore.
**Result**
The correct team will be assigned for PR review
=> build(shipjs): update PR team reviewer

CHANGELOG.md, package.json, src/version.ts
This is the final release of Angular InstantSearch.
=> chore: release 4.4.3
